name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Install pnpm (This was commented out in your snippet)
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # Or 8, depending on what you use locally

      # 2. Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies using pnpm
      - name: Install dependencies
        run: |
          rm -f pnpm-lock.yaml
          pnpm install

      # 4. Build the site
      - name: build
        env:
          # This passes your repo name to your svelte.config.js
          # BASE_PATH: '/${{ github.event.repository.name }}'
          # Custom Domain:
          BASE_PATH: ''
        run: |
          pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4